/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as PaymentsSuccessRouteImport } from './routes/payments.success'
import { Route as PaymentsFailureRouteImport } from './routes/payments.failure'
import { Route as ManageSettingsRouteImport } from './routes/manage.settings'
import { Route as ManageReportsRouteImport } from './routes/manage.reports'
import { Route as ManageRefundsRouteImport } from './routes/manage.refunds'
import { Route as ManageHotelsRouteImport } from './routes/manage.hotels'
import { Route as ManageBookingsRouteImport } from './routes/manage.bookings'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as CheckoutBookingIdRouteImport } from './routes/checkout.$bookingId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as ManageHotelsIndexRouteImport } from './routes/manage.hotels.index'
import { Route as ManageHotelsNewRouteImport } from './routes/manage.hotels.new'
import { Route as ManageHotelsHotelIdRouteImport } from './routes/manage.hotels.$hotelId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsSuccessRoute = PaymentsSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsFailureRoute = PaymentsFailureRouteImport.update({
  id: '/payments/failure',
  path: '/payments/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSettingsRoute = ManageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManageRoute,
} as any)
const ManageReportsRoute = ManageReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManageRoute,
} as any)
const ManageRefundsRoute = ManageRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => ManageRoute,
} as any)
const ManageHotelsRoute = ManageHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => ManageRoute,
} as any)
const ManageBookingsRoute = ManageBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ManageRoute,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutBookingIdRoute = CheckoutBookingIdRouteImport.update({
  id: '/checkout/$bookingId',
  path: '/checkout/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageHotelsIndexRoute = ManageHotelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageHotelsRoute,
} as any)
const ManageHotelsNewRoute = ManageHotelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ManageHotelsRoute,
} as any)
const ManageHotelsHotelIdRoute = ManageHotelsHotelIdRouteImport.update({
  id: '/$hotelId',
  path: '/$hotelId',
  getParentRoute: () => ManageHotelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guests': typeof GuestsRoute
  '/manage': typeof ManageRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/hotels': typeof ManageHotelsRouteWithChildren
  '/manage/refunds': typeof ManageRefundsRoute
  '/manage/reports': typeof ManageReportsRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/bookings/': typeof BookingsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/hotels/$hotelId': typeof ManageHotelsHotelIdRoute
  '/manage/hotels/new': typeof ManageHotelsNewRoute
  '/manage/hotels/': typeof ManageHotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guests': typeof GuestsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/refunds': typeof ManageRefundsRoute
  '/manage/reports': typeof ManageReportsRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/bookings': typeof BookingsIndexRoute
  '/manage': typeof ManageIndexRoute
  '/manage/hotels/$hotelId': typeof ManageHotelsHotelIdRoute
  '/manage/hotels/new': typeof ManageHotelsNewRoute
  '/manage/hotels': typeof ManageHotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guests': typeof GuestsRoute
  '/manage': typeof ManageRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/hotels': typeof ManageHotelsRouteWithChildren
  '/manage/refunds': typeof ManageRefundsRoute
  '/manage/reports': typeof ManageReportsRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/bookings/': typeof BookingsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/hotels/$hotelId': typeof ManageHotelsHotelIdRoute
  '/manage/hotels/new': typeof ManageHotelsNewRoute
  '/manage/hotels/': typeof ManageHotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/guests'
    | '/manage'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/wishlist'
    | '/bookings/$bookingId'
    | '/checkout/$bookingId'
    | '/hotels/$hotelId'
    | '/manage/bookings'
    | '/manage/hotels'
    | '/manage/refunds'
    | '/manage/reports'
    | '/manage/settings'
    | '/payments/failure'
    | '/payments/success'
    | '/bookings/'
    | '/manage/'
    | '/manage/hotels/$hotelId'
    | '/manage/hotels/new'
    | '/manage/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/guests'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/wishlist'
    | '/bookings/$bookingId'
    | '/checkout/$bookingId'
    | '/hotels/$hotelId'
    | '/manage/bookings'
    | '/manage/refunds'
    | '/manage/reports'
    | '/manage/settings'
    | '/payments/failure'
    | '/payments/success'
    | '/bookings'
    | '/manage'
    | '/manage/hotels/$hotelId'
    | '/manage/hotels/new'
    | '/manage/hotels'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/guests'
    | '/manage'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/wishlist'
    | '/bookings/$bookingId'
    | '/checkout/$bookingId'
    | '/hotels/$hotelId'
    | '/manage/bookings'
    | '/manage/hotels'
    | '/manage/refunds'
    | '/manage/reports'
    | '/manage/settings'
    | '/payments/failure'
    | '/payments/success'
    | '/bookings/'
    | '/manage/'
    | '/manage/hotels/$hotelId'
    | '/manage/hotels/new'
    | '/manage/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuestsRoute: typeof GuestsRoute
  ManageRoute: typeof ManageRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  WishlistRoute: typeof WishlistRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  CheckoutBookingIdRoute: typeof CheckoutBookingIdRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  PaymentsFailureRoute: typeof PaymentsFailureRoute
  PaymentsSuccessRoute: typeof PaymentsSuccessRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof PaymentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/failure': {
      id: '/payments/failure'
      path: '/payments/failure'
      fullPath: '/payments/failure'
      preLoaderRoute: typeof PaymentsFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/settings': {
      id: '/manage/settings'
      path: '/settings'
      fullPath: '/manage/settings'
      preLoaderRoute: typeof ManageSettingsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/reports': {
      id: '/manage/reports'
      path: '/reports'
      fullPath: '/manage/reports'
      preLoaderRoute: typeof ManageReportsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/refunds': {
      id: '/manage/refunds'
      path: '/refunds'
      fullPath: '/manage/refunds'
      preLoaderRoute: typeof ManageRefundsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/hotels': {
      id: '/manage/hotels'
      path: '/hotels'
      fullPath: '/manage/hotels'
      preLoaderRoute: typeof ManageHotelsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/bookings': {
      id: '/manage/bookings'
      path: '/bookings'
      fullPath: '/manage/bookings'
      preLoaderRoute: typeof ManageBookingsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$bookingId': {
      id: '/checkout/$bookingId'
      path: '/checkout/$bookingId'
      fullPath: '/checkout/$bookingId'
      preLoaderRoute: typeof CheckoutBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/hotels/': {
      id: '/manage/hotels/'
      path: '/'
      fullPath: '/manage/hotels/'
      preLoaderRoute: typeof ManageHotelsIndexRouteImport
      parentRoute: typeof ManageHotelsRoute
    }
    '/manage/hotels/new': {
      id: '/manage/hotels/new'
      path: '/new'
      fullPath: '/manage/hotels/new'
      preLoaderRoute: typeof ManageHotelsNewRouteImport
      parentRoute: typeof ManageHotelsRoute
    }
    '/manage/hotels/$hotelId': {
      id: '/manage/hotels/$hotelId'
      path: '/$hotelId'
      fullPath: '/manage/hotels/$hotelId'
      preLoaderRoute: typeof ManageHotelsHotelIdRouteImport
      parentRoute: typeof ManageHotelsRoute
    }
  }
}

interface ManageHotelsRouteChildren {
  ManageHotelsHotelIdRoute: typeof ManageHotelsHotelIdRoute
  ManageHotelsNewRoute: typeof ManageHotelsNewRoute
  ManageHotelsIndexRoute: typeof ManageHotelsIndexRoute
}

const ManageHotelsRouteChildren: ManageHotelsRouteChildren = {
  ManageHotelsHotelIdRoute: ManageHotelsHotelIdRoute,
  ManageHotelsNewRoute: ManageHotelsNewRoute,
  ManageHotelsIndexRoute: ManageHotelsIndexRoute,
}

const ManageHotelsRouteWithChildren = ManageHotelsRoute._addFileChildren(
  ManageHotelsRouteChildren,
)

interface ManageRouteChildren {
  ManageBookingsRoute: typeof ManageBookingsRoute
  ManageHotelsRoute: typeof ManageHotelsRouteWithChildren
  ManageRefundsRoute: typeof ManageRefundsRoute
  ManageReportsRoute: typeof ManageReportsRoute
  ManageSettingsRoute: typeof ManageSettingsRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageBookingsRoute: ManageBookingsRoute,
  ManageHotelsRoute: ManageHotelsRouteWithChildren,
  ManageRefundsRoute: ManageRefundsRoute,
  ManageReportsRoute: ManageReportsRoute,
  ManageSettingsRoute: ManageSettingsRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuestsRoute: GuestsRoute,
  ManageRoute: ManageRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  WishlistRoute: WishlistRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  CheckoutBookingIdRoute: CheckoutBookingIdRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  PaymentsFailureRoute: PaymentsFailureRoute,
  PaymentsSuccessRoute: PaymentsSuccessRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
